export const adminAuthority = [
  {
    module_name: "/user-role-management",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/patient-registration",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/patient-basic-history",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/patient-extended-history",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/male-infertility-investigation",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/female-infertility-investigation",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  // { module_name: "/basic-semen-analysis", create: true, delete: false, edit: true, view_only: true },
  {
    module_name: "/ivf-flow-sheet",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/embryology-data-sheet",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/luteal-phase",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  // {
  //   module_name: "/vitrification-data-sheet",
  //   create: true,
  //   delete: false,
  //   edit: true,
  //   view_only: true,
  // },
  // {
  //   module_name: "/embryo-warming-data-sheet",
  //   create: true,
  //   delete: false,
  //   edit: true,
  //   view_only: true,
  // },
  {
    module_name: "/cycle-out-come",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/discharge-card",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/tesa-pesa-discharge-card",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/pgs-discharge-card",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
];
export const seniorEmbryoAuthority = [
  {
    module_name: "/user-role-management",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/patient-registration",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/patient-basic-history",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/patient-extended-history",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/male-infertility-investigation",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/female-infertility-investigation",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  // { module_name: "/basic-semen-analysis", create: true, delete: false, edit: true, view_only: true },
  {
    module_name: "/ivf-flow-sheet",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/embryology-data-sheet",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/luteal-phase",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  // {
  //   module_name: "/vitrification-data-sheet",
  //   create: true,
  //   delete: false,
  //   edit: true,
  //   view_only: true,
  // },
  // {
  //   module_name: "/embryo-warming-data-sheet",
  //   create: true,
  //   delete: false,
  //   edit: true,
  //   view_only: true,
  // },
  {
    module_name: "/cycle-out-come",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/discharge-card",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/tesa-pesa-discharge-card",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/pgs-discharge-card",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
];

export const juniorEmbryoAuthority = [
  {
    module_name: "/patient-registration",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/patient-basic-history",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/patient-extended-history",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/male-infertility-investigation",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/female-infertility-investigation",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  // { module_name: "/basic-semen-analysis", create: true, delete: false, edit: true, view_only: true },
];

export const seniorConsultantAuthority = [
  {
    module_name: "/user-role-management",
    create: false,
    delete: false,
    edit: false,
    view_only: true,
  },
  {
    module_name: "/patient-registration",
    create: false,
    delete: false,
    edit: false,
    view_only: true,
  },
  {
    module_name: "/patient-basic-history",
    create: false,
    delete: false,
    edit: false,
    view_only: true,
  },
  {
    module_name: "/patient-extended-history",
    create: false,
    delete: false,
    edit: false,
    view_only: true,
  },
  {
    module_name: "/male-infertility-investigation",
    create: false,
    delete: false,
    edit: false,
    view_only: true,
  },
  {
    module_name: "/female-infertility-investigation",
    create: false,
    delete: false,
    edit: false,
    view_only: true,
  },
  // { module_name: "/basic-semen-analysis", create: false, delete: false, edit: false, view_only: true },
  {
    module_name: "/ivf-flow-sheet",
    create: false,
    delete: false,
    edit: false,
    view_only: true,
  },
  {
    module_name: "/embryology-data-sheet",
    create: false,
    delete: false,
    edit: false,
    view_only: true,
  },
  {
    module_name: "/luteal-phase",
    create: false,
    delete: false,
    edit: false,
    view_only: true,
  },
  // {
  //   module_name: "/vitrification-data-sheet",
  //   create: false,
  //   delete: false,
  //   edit: false,
  //   view_only: true,
  // },
  // {
  //   module_name: "/embryo-warming-data-sheet",
  //   create: false,
  //   delete: false,
  //   edit: false,
  //   view_only: true,
  // },
  {
    module_name: "/cycle-out-come",
    create: false,
    delete: false,
    edit: false,
    view_only: true,
  },
  {
    module_name: "/discharge-card",
    create: false,
    delete: false,
    edit: false,
    view_only: true,
  },
  {
    module_name: "/tesa-pesa-discharge-card",
    create: false,
    delete: false,
    edit: false,
    view_only: true,
  },
  {
    module_name: "/pgs-discharge-card",
    create: false,
    delete: false,
    edit: false,
    view_only: true,
  },
];

export const assistantDoctorAuthority = [
  {
    module_name: "/patient-registration",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/patient-basic-history",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/patient-extended-history",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/male-infertility-investigation",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/female-infertility-investigation",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/ivf-flow-sheet",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/luteal-phase",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/cycle-out-come",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/discharge-card",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/tesa-pesa-discharge-card",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/pgs-discharge-card",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
];

export const cceAuthority = [
  {
    module_name: "/patient-registration",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/patient-basic-history",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/patient-extended-history",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/male-infertility-investigation",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
  {
    module_name: "/female-infertility-investigation",
    create: true,
    delete: false,
    edit: true,
    view_only: true,
  },
];
